import type { DemoTemplate } from "../demoTypes";
import { makeCalendar, makeLiquidity, probabilityPalette, riskMatrixBase } from "./shared";

export const kobiTemplate: DemoTemplate = {
  sector: "kobi",
  baselineVolume: 60_000_000,
  baselineNakit: 600_000,
  baselineOpex: 970_000,
  baselineVade: 60,
  baselineMusteri: 85,
  baselinePesin: 30,
  baselineRisk: 18,
  kpis: [
    {
      id: "cashForecast12w",
      title: "12 Haftalık Nakit Tahmini",
      baselineAmount: 18_500_000,
      format: "tl",
      trend: { label: "+%12.4 (ilk 4 haftaya göre)", type: "up" },
      scale: true,
    },
    {
      id: "weeklyNetCash",
      title: "Haftalık Net Nakit",
      baselineAmount: 145_000,
      format: "tl",
      subtext: { label: "Likidite Durumu: Gergin", color: "orange" },
      scale: true,
    },
    {
      id: "cashRunway",
      title: "Nakit Ömrü (Cash Runway)",
      baselineAmount: 21,
      format: "days",
      badge: { label: "🚨 Teşhis: Müşteri Yoğunlaşma" },
      scale: false,
    },
    {
      id: "totalRecoverable",
      title: "Toplam Kurtarılabilir",
      baselineAmount: 3_450_000,
      format: "tl",
      subtext: { label: "Geç Ödeme Oranı: %42.1", color: "orange" },
      scale: true,
    },
  ],
  charts: {
    liquidity: makeLiquidity([18, 19, 17, 20, 18, 22, 21, 24, 23, 26, 24, 28], 4),
    waterfall: [
      { name: "Başlangıç", value: [0, 600], isTotal: true },
      { name: "Tahsilatlar", value: [600, 820] },
      { name: "Yeni Satış", value: [820, 970] },
      { name: "Tedarik Ödemeleri", value: [970, 780] },
      { name: "Maaş / Kira", value: [780, 650] },
      { name: "Beklenen Kapanış", value: [0, 650], isTotal: true },
    ],
    riskMatrix: riskMatrixBase,
    concentration: [
      { name: "Perakende", value: 120, fullMark: 150 },
      { name: "İnşaat", value: 95, fullMark: 150 },
      { name: "Gıda", value: 70, fullMark: 150 },
      { name: "Tekstil", value: 105, fullMark: 150 },
      { name: "Otomotiv", value: 55, fullMark: 150 },
      { name: "Hizmet", value: 40, fullMark: 150 },
    ],
    calendar: makeCalendar(["15", "20", "23"]),
  },
  topOffenders: [
    { id: 1, name: "Özçelik Yapı Market", score: 88, amount: 425_000 },
    { id: 2, name: "Anadolu Tekstil Koll. Şti.", score: 82, amount: 310_000 },
    { id: 3, name: "Güneş Gıda Dağıtım", score: 78, amount: 185_000 },
    { id: 4, name: "Mavi Deniz Ticaret Ltd.", score: 74, amount: 142_000 },
    { id: 5, name: "Akdeniz Otomotiv Yedek", score: 71, amount: 98_000 },
  ],
  workOrders: [
    { id: "k1", customerName: "Özçelik Yapı Market", urgency: "KRİTİK", amount: 425_000, costOfInactionMonthly: 28_500, aiSuggestion: "DBS zorunlu tut, açık hesabı kapat ve çek vade gününü öne çek." },
    { id: "k2", customerName: "Anadolu Tekstil Koll. Şti.", urgency: "KRİTİK", amount: 310_000, costOfInactionMonthly: 18_200, aiSuggestion: "Senet karşılığı vadeyi 15 gün kısalt, kefil teminatı talep et." },
    { id: "k3", customerName: "Güneş Gıda Dağıtım", urgency: "YÜKSEK", amount: 185_000, costOfInactionMonthly: 8_400, aiSuggestion: "Limit %20 daralt, haftalık sipariş tavanı uygula." },
    { id: "k4", customerName: "Mavi Deniz Ticaret Ltd.", urgency: "ORTA", amount: 142_000, costOfInactionMonthly: 3_100, aiSuggestion: "Peşin ödeme iskontosu öner (%2), dinamik iskonto aktifleştir." },
    { id: "k5", customerName: "Akdeniz Otomotiv Yedek", urgency: "ORTA", amount: 98_000, costOfInactionMonthly: 2_250, aiSuggestion: "Risk skoru yükselişte — standart izlemede tut." },
  ],
  strategy: {
    runs: [
      { id: "20260404_1849", date: "04 Nisan 2026 - 18:49", urgency: "DÜŞÜK", status: "GREEN", portfolioRisk: 0.36, totalExposure: 12_500_000, accountsFlagged: 6, isLatest: true },
      { id: "20260328_0900", date: "28 Mart 2026 - 09:00", urgency: "ORTA", status: "YELLOW", portfolioRisk: 0.41, totalExposure: 13_100_000, accountsFlagged: 8, isLatest: false },
      { id: "20260321_0900", date: "21 Mart 2026 - 09:00", urgency: "YÜKSEK", status: "RED", portfolioRisk: 0.58, totalExposure: 14_800_000, accountsFlagged: 11, isLatest: false },
    ],
    detail: {
      executiveSummary: "KOBİ portföyünde en kritik sinyal Özçelik Yapı Market hesabındaki 425.000 TL açık pozisyondur. Senet karşılığı yapılandırma + DBS zorunluluğu ile 2.850.000 TL toplam kurtarım potansiyeli mevcut. Haftalık 28.500 TL inaksiyon maliyeti hızla birikiyor.",
      metrics: {
        totalExposure: 12_500_000,
        forecast12w: 18_500_000,
        weeklyAvg: 1_541_000,
        netCashWeekly: 145_000,
        portfolioRisk: 0.36,
        latePaymentPct: 42.1,
        trend: "%12 Artış",
      },
      impactAnalysis: {
        inactionCostWeekly: 62_450,
        totalInvoicesAffected: 320,
        departmentLoad: [
          { dept: "Tahsilat Birimi", taskCount: 3, label: "Kıdemli Uzman / Koordinatör" },
          { dept: "Satış Operasyonları", taskCount: 2, label: "Müşteri Başarı Uzmanı" },
        ],
      },
      recoveryAnalysis: {
        funnel: [
          { label: "Yönetilen Riskli Pozisyon", value: 4_200_000, color: "bg-amber-500", width: "100%" },
          { label: "AI Hedeflenen Kurtarım", value: 2_850_000, color: "bg-emerald-500", width: "68%" },
          { label: "Beklenen Risk Payı (Kayıp)", value: 1_350_000, color: "bg-red-500", width: "32%" },
        ],
        matrix: [
          { id: "K95", x: 120, y: 4.2, risk: 0.42, label: "Özçelik" },
          { id: "K78", x: 95, y: 3.1, risk: 0.31, label: "Anadolu" },
          { id: "K42", x: 72, y: 1.85, risk: 0.28, label: "Güneş" },
          { id: "K19", x: 55, y: 1.42, risk: 0.22, label: "Mavi" },
        ],
      },
      scenarios: [
        { id: 1, isRecommended: true, name: "Senaryo 1: Kademeli KOBİ Tahsilatı", description: "Her hesap kendi tier'ına göre kalibre edilmiş müdahale alır. Senet takibi + DBS geçişi önceliği.", expectedRecovery: 2_850_000, timeframe: "30-45 gün", clientLossRisk: "%8-12", cost: "İskonto Maliyeti: 95.000 TL" },
        { id: 2, isRecommended: false, name: "Senaryo 2: Agresif Senet Protesto", description: "Tüm vadesi geçmiş çek/senetler protesto edilir. Hızlı nakit ama bayi ilişkisi kalıcı hasar.", expectedRecovery: 2_680_000, timeframe: "15-25 gün", clientLossRisk: "%30-45", cost: "Hukuki Maliyet: 42.000 TL" },
      ],
      pipelineDetails: {
        triggerLog: "Modül 1 → Risk 0.36 + Modül 3 → GREEN",
        confidence: "%82",
        urgency: "ORTA",
        timestamp: "2026-04-04T18:49:00",
        weakestLink: 98_000,
        strongestLink: 425_000,
        cashFlow: { weekly: 145_000, monthly: 628_000, quarterly: 1_885_000 },
      },
      accounts: [
        { id: "K095", name: "Özçelik Yapı Market", tier: 1, exposure: 425_000, riskBucket: "Medium Risk", overdue: 92, expectedRecovery: 298_000, actionType: "FORMAL DEMAND", aiInstruction: "Yapı Market sahibini bugün ara; 92 günlük gecikme için DBS zorunlu tut.", financialRationale: "Haftalık 28.500 TL finansman yükü yaratıyor; 60 gün daha beklenirse batık riski %55'e çıkıyor.", relationshipNote: "10 yıllık bayi; sezon sonu kampanyalarında büyük cirolar getiriyor. Hukuki sürece gitmeden yapılandırma şansı verilmeli.", steps: [{ id: "K095-s1", day: "Gün 1", title: "Bayi sahibini ara, DBS sunumunu yap", aiInstruction: "Telefonda DBS faydalarını anlat, otomatik talimat formunu ilet." }, { id: "K095-s2", day: "Gün 3", title: "Senet karşılığı yapılandırma sun", aiInstruction: "3 eşit taksit önerisi hazırla, kefil istemesi konusu müzakereye açık." }, { id: "K095-s3", day: "Gün 7", title: "Limit %30 daralt", aiInstruction: "ERP'de açık hesap limitini düşür." }] },
        { id: "K078", name: "Anadolu Tekstil Koll. Şti.", tier: 2, exposure: 310_000, riskBucket: "Medium Risk", overdue: 78, expectedRecovery: 220_000, actionType: "BLOCK & RESTRUCTURE", aiInstruction: "Açık hesap satışını blokla, senet karşılığı yapılandırma ilet.", financialRationale: "Haftalık 18.200 TL yük; 45 gün daha beklenirse ek 81.000 TL kayıp.", relationshipNote: "Tekstil sezonu öncesi hassas dönem; siparişi kesmeden çözüm aranmalı.", steps: [{ id: "K078-s1", day: "Gün 1", title: "Açık hesap satışı bloklanır", aiInstruction: "ERP engeli koy." }, { id: "K078-s2", day: "Gün 5", title: "Senet karşılığı yapılandırma önerisi", aiInstruction: "3 ay 4 taksit senet teklifi." }] },
      ],
    },
  },
  kanban: [
    { id: "K095", company: "Özçelik Yapı Market", exposure: 425_000, delay: "92 Gün", risk: "Orta (0.42)", action: "Yapılandırma Teklifi Sunuldu", status: "Bekliyor", filterCategory: "bekleyen" },
    { id: "K078", company: "Anadolu Tekstil Koll. Şti.", exposure: 310_000, delay: "78 Gün", risk: "Orta (0.31)", action: "Müzakere Devam Ediyor", status: "İşlemde", filterCategory: "aktif" },
    { id: "K042", company: "Güneş Gıda Dağıtım", exposure: 185_000, delay: "55 Gün", risk: "Orta (0.28)", action: "7. Gün Taahhüt İhlali", status: "SLA Aşımı", filterCategory: "zaman_asimi" },
    { id: "K019", company: "Mavi Deniz Ticaret Ltd.", exposure: 98_000, delay: "140 Gün", risk: "Yüksek (0.72)", action: "Yapılandırma Reddedildi", status: "Reddedildi / Hukuk", filterCategory: "riskli" },
  ],
  accountProfile: {
    id: "K095",
    name: "Özçelik Yapı Market",
    exposure: 425_000,
    expectedRecovery: 298_000,
    weeklyInactionCost: 28_500,
    delayDays: 92,
    riskScore: 0.42,
    riskBucket: "Orta Risk",
    assignedRole: "Kıdemli Tahsilat Uzmanı",
    module1: {
      probability: [
        { name: probabilityPalette[0].name, val: 8, color: probabilityPalette[0].color },
        { name: probabilityPalette[1].name, val: 12, color: probabilityPalette[1].color },
        { name: probabilityPalette[2].name, val: 22, color: probabilityPalette[2].color },
        { name: probabilityPalette[3].name, val: 25, color: probabilityPalette[3].color },
        { name: probabilityPalette[4].name, val: 20, color: probabilityPalette[4].color },
        { name: probabilityPalette[5].name, val: 13, color: probabilityPalette[5].color },
      ],
      invoices: [
        { id: "INV-2025-0412", date: "10.01.2026", amount: 185_000, daysDelay: "-92 Gün", statusText: "Kritik Gecikme", statusType: "critical" },
        { id: "INV-2025-0388", date: "28.12.2025", amount: 140_000, daysDelay: "-105 Gün", statusText: "Kritik Gecikme", statusType: "critical" },
        { id: "INV-2025-0345", date: "15.12.2025", amount: 100_000, daysDelay: "-118 Gün", statusText: "Ağır Gecikme", statusType: "severe" },
      ],
    },
    module3: {
      cashGapBefore: 38,
      cashGapAfter: 54,
      runwayBefore: 21,
      runwayAfter: 16,
      gapDeltaPct: 16,
      runwayDeltaDays: 5,
    },
  },
};
